version: '3.8'

services:
  postgres:
    container_name: nest-fastfeet-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-fastfeet

  cache:
    container_name: nest-fastfeet-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data